### ISSUE TITLE
You may find my writeup here also useful https://www.reddit.com/r/TIdaL/s/nbqVaQhAHo

### ISSUE THREAD

**Issue by heartmeeting** [Inrixia/neptune-plugins#24]
I've read the write-up and your comments and it is really helpful.  There's one last bit I am still trying to grasp.

I am playing MQA files that I know were originally sampled at 192kHz and 352.8kHz - UAPP reports them as such (so does Roon according to the free trial I had, now expired).  I'm using a Dragonfly Red which of course is a renderer only after Tidal's done its work.

TidalTags shows it as 24bit 44.1kHZ - so once I've mentally doubled that to 88.2kHZ it isn't clear from TidalTags what multiple is then being offered through the rendering to take it to the originally sampled rate.

Since UAPP and Roon can see the original sampled rate, which represents the fully rendered value, is this not something that TidalTags could also do?

Thanks - I'm hopefully not annoying you too much!

(p.s. I tried to reply via Discord but it says I don't have permission to send messages in that channel)

**Comment by Inrixia** [comment]
If you have a MQA DAC that supports hardware unfolding then it will do additional unfolding from 88.2kHz to 352.8kHz (x4) for example.

From what I understand for this to happen you need to ensure that software unfolding is disabled in Tidal settings so so your DAC does it. You can refer to the signal light on your DAC or whatever it has to determine if its doing full hardware unfolding.

Also I added a note in the #helpful-resources channel about how to chat as I presume that's why you weren't able to, do let me know if this wasn't the case or dm me :)

If you have any further questions please do followup here. Ill close this for now but you can continue to comment here.
