### ISSUE TITLE
SongDownloader - Downloading large file causes GUI crash

### ISSUE THREAD

**Issue by sunspot478** [Inrixia/neptune-plugins#28]
Hi,

I checked existing and solved issues and didn't see one like this.  If there is, I apologize.
I'm running Windows 10 22H2 19045.4291, all drivers up to date.  

I recently tried to download a fairly large file and it has caused a GUI crash every time.  The file in question is:
https://tidal.com/browse/track/55391798?u

It is a 24bit 192kHz FLAC, which at over 13 minutes long is about 525 MB.  When the download hits 100%, instead of showing the folder selection dialog, the GUI will simply disappear.  No error messages, no warning, just disappears as if closed.  Checking open processes, all of the Tidal.exe and TidalPlayer.exe processes still appear to be running and if you happen to be listening to a track, it will still play on.  If you try to restart the GUI at this point, the application will load up the window, but it will stay completely blank (and the song will still keep playing.)  The only way to get the GUI back so that you can actually use it is to kill all Tidal process and restart the application.

I would guess that this issue would seem to be related to file size as other files download okay that are not as large.  (Maybe 512MB is a limit?)
Thanks,
Jamie

**Comment by Inrixia** [comment]
Can reproduce this, will see if I can figure out why its happening. Thx

**Comment by Inrixia** [comment]
Thx for reporting this! Reopen if its not resolved <3

**Comment by sunspot478** [comment]
Resolved on my end.  Thank you!

**Comment by sunspot478** [comment]
Owwww!   Wow.  I just want to take a moment and acknowledge how incredibly FRICKIN' fast this issue was resolved.  I typed up the "complaint" before I went to bed ... didn't think much of it.  If I need to use a "High" copy of the song, I will.  Whatever.  I go to bed, sleep for 7 hours... I go to bed and whiel I'm sleeping, Inrixia is like... "Ohh, ya, I get ya.  Happened to me too.  Lemme get back to ya!"

Badda-bing, badda-bang.

I wake up and ... Inrixia is like .... Issue fixed.  So I try and ... So it is.  Outstanding.  Whatever you're paying this person, it should be doubled. 

CHEERS!

**Comment by sunspot478** [comment]
Re-opening this one ...

Hi,

Experiencing an issue, similar to before, where the Tidal GUI is freezing/crashing/erroring out when trying to download a particularly large file.  Before, it was Shine On You Crazy Diamond Parts 1-5 by Pink Floyd which was about 550 MB or so.   Floyd strikes again ...

Only "Echoes" this time.  At 24/192, the entire song is good for 855 MB:

![image](https://github.com/Inrixia/neptune-plugins/assets/158432343/aacf1b06-7e0c-4190-bc63-29867de8af54)

But when it reaches 100%, it will show this:

![image](https://github.com/Inrixia/neptune-plugins/assets/158432343/b65f580b-b7c4-40ac-80a2-f1a9816bba24)

If you try to download it again, it will freeze and/or crash the GUI.  Seems reasonable to assume this is a file size related issue, since all of the other files on that album download okay.

**Comment by Inrixia** [comment]
Does it fail before or after its 100% downloaded?

If you set a download path in the settings does it still fail?

**Comment by sunspot478** [comment]
After 100%, presumably when trying to write the file.  
And... Yes, path set.

Did a test just now without the path set.  Same error, after it gets to 100%

**Comment by Inrixia** [comment]
AHAHAHAHAHAHAHAHAHA so its finally done. SongDownloader finally now is using streams from end to end (Unless you use browser prompted save but more on that) 

- Switch to streams 6101a06364140bb22712f32ac6293c5a35d4585b
- Make browser prompt use Blobs so it doesn't crash if download path isnt set 9485f903f1647568b841b718de887df963d1c322

#### Casually rewrite/port the flac-tagger library to work natively with streams
https://github.com/Inrixia/flac-stream-tagger/commit/4b5d5580989547cc3961ae88a9c1418dc541c3ed, https://github.com/Inrixia/flac-stream-tagger/commit/af9f8e18e9918d4677e981a9f834af64bc068377, https://github.com/Inrixia/flac-stream-tagger/commit/e014c2e596a617730fa0d9c94233b55881bc7a6a

As of now both **Browser Prompted** and **Native** (When you have **Download Path** set) are working with massive files (I've been testing using Echoes).

**Native** downloads also have the benefit of being fully streamed now so the data will literally appear on file as its processed chunk by chunk.

**Browser Prompted** still has to aggregate to a **Blob** for the browser before saving to disk (due to Neptune limitations that should be being fixed soonTM @twnlink native access when ❤️)

But TLDR: It works!

If you have **Download Path** set you should be guaranteed to not have any issues. Otherwise I haven't been able to break **Browser Prompted** yet.

This was a ton of work to get sorted but I'm super happy with it, and its so cool to have the entire download/decode/flag metadata process be streamed direct to disk!

Thanks again for letting me know about this, and do continue to reach out if you find things!

**Comment by Inrixia** [comment]
As of today Neptune now has native support! This means that folder prompting is now possible, and that all downloads will be done fully native side (out of the browser). This brings a nice speedup and performance improvement and also means that all downloads can be fully stream based and not have to rely on converting to a Blob when saving.

As songs are now streamed to disk as they are downloaded I doubt file size will be a issue going forwards :)
