### ISSUE TITLE
[Suggestion] [TidalTags]: Let plugin fill up the playlist with audio quality info without the need to manually play each song in the playlist

### ISSUE THREAD

**Issue by Skubers** [Inrixia/neptune-plugins#39]
Right now, the plugin fills up the information only after the song has been played (and not always too, see this issue: https://github.com/Inrixia/neptune-plugins/issues/38)

![image](https://github.com/user-attachments/assets/a85395dd-f201-420b-a948-5540cacca885)

The idea is to let the plugin fill up these information without the need to manually play all the songs in the playlist.

**Comment by sunspot478** [comment]
I was actually thinking about this exact same thing, but I thought that since it appears the info isn't acquired until the track is actually played (and header info acquired,) I can't see there being a way to have it do this without polling every track on the playlist.  That strikes me as something that would be VERY resource-intensive.  But hey... Whaddo I know? =]

**Comment by Inrixia** [comment]
@sunspot478 not resource intensive. But I'm avoidant to hitting the tidal cdn in that way.

Easy to do and I'll eventually implement it imo (why this is still open) but I will want to implement a random delay of probably 1-5 seconds between each track.

Thankfully for 99% of tracks getting the track info does not require fetching the entire track, most only need a head request to the cdn to get filesize, and few require either the track or first couple hundred bytes.

**Comment by Inrixia** [comment]
@sunspot478 not resource intensive. But I'm avoidant to hitting the tidal cdn in that way.

Easy to do and I'll eventually implement it imo (why this is still open) but I will want to implement a random delay of probably 1-5 seconds between each track.

Thankfully for 99% of tracks getting the track info does not require fetching the entire track, most only need a head request to the cdn to get filesize, and few require either the track or first couple hundred bytes.

**Comment by Inrixia** [comment]
Going to close this as not planned as there are properties that are retrieved when playing a track (duration etc) which are not possible to get otherwise.

While handling cases where this information isnt available already exists, it requires grabbing enough of the track to do a full metadata decode. So really just skipping through each track would be faster anyway.
