### ISSUE TITLE
[BUG] [Song Downloader] - Filename & folders break on special characters

### ISSUE THREAD

**Issue by mihainemethi** [Inrixia/neptune-plugins#48]
Hello. I tried https://inrixia.github.io/neptune-plugins/SongDownloader/ but it doesn't download all my song name. I added artist - title in the border but it doesn't give me the full name or the name of the artist and the song
![Screenshot 2024-07-31 201927](https://github.com/user-attachments/assets/deb373e5-0e7d-4fe4-a108-b1639570aa3d)
![Screenshot 2024-07-31 202641](https://github.com/user-attachments/assets/043a3d08-4850-4f35-95cf-1d8122ea381b)
![Screenshot 2024-07-31 203800](https://github.com/user-attachments/assets/a591bd94-e819-43a8-8632-838441ac2d46)

so far I have noticed these 2 songs. but there are also others that do not download them with the full name that is displayed on Tidal

https://tidal.com/browse/track/77623632?u
https://tidal.com/browse/track/180788209?u

**Comment by sunspot478** [comment]
I've experienced a similar issue with Downloader.  First, my downloader settings:
[Please ignore the extra "Tidal-FLAC-etc"  It's for my own personal use]

![image](https://github.com/user-attachments/assets/9ef8ec18-fdc0-412a-9ed8-189e50f05642)

What happens is that, when downloading, a new directory is formed with my default folder, and then the filename is named with a portion of the title.  There are two songs that this has happened on:

https://tidal.com/browse/track/15875451?u
https://tidal.com/browse/track/3730396?u

Upon looking at the tags for both of those downloaded files, I noticed that both have a "/" in the title.  It looks like Downloader is interpreting THAT / as marking a separate directory.  It creates the directory within the default directory with all the text before the / and then names the file with all the text after the /.

Also of note was the relative difficulty of deleting the created directory afterwards in the first example.  I think because there was a space between the text and the /.  It required an elevated command prompt and some DOS 6.1 commands circa 1996 or so.  Good times.

...Jamie
